name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: time-api:latest
    
    - name: Test Docker container
      run: |
        docker run --rm -d -p 8000:8000 --name test-container time-api:latest
        sleep 5
        curl -f http://localhost:8000/health || exit 1
        docker stop test-container 